### PR TITLE
PR for testing tic-tac-toe

### PR DESCRIPTION
**Pull request by praz99**
In this branch, we

- tested the methods in Game, Players, and Board class.
- used RSpec for testing.
- tested all the methods for all possible input and output conditions as far as possible.

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull request under the review by Maria Eugenia Queme P. (TSE)

### Hello @praz99 and @ozovalihasan  :lollipop: :balloon: 

### Thank you for your submission :handshake: you've done a great work creating test cases for all the methods of your tic-tac-toe project, I believe you've followed the best practices and overall you understood the main concepts of the project so you should feel very proud of your work :1st_place_medal: :1st_place_medal: there is just one aspect I'd like you to work on :construction: :construction_worker: :construction_worker: 

## Project-specific

- [x] specs cover positive and negative scenarios ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)) 

all your `it` descriptions are very general each test case either has a positive or a negative outcome so modify your `it` descriptions so they are positive or negative and add the positive or negative `it` block counterpart for example:

this general test case you have:

```ruby
  describe '#check_valid' do
    it 'checks the value of board in given position to be integer.' do
      expect(new_board.check_valid(3)).to eql true
    end
  end
```
can be changed to positive and negative like this:
```ruby
  describe '#check_valid' do
    it 'returns true if the value of board in a given position is an Integer.' do
      expect(new_board.check_valid(3)).to eql true
    end

    it "doesn't return true if the value of board in a given position is not an Integer." do
      expect(new_board.check_valid(3)).not_to eql true
    end
  end
```
now it's clear what is the positive and what is the negative test case, so let's do it for all of your test cases at least the ones that do something depending on the parameter they receive.

### That's it, team! :raised_hands: 

### Please do that changes :technologist: :technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Comment by ozovalihasan** [comment]
Thank you for your feedback @euqueme .

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### You have done great and for making changes from the previous review :clap: The test passes and your project has been approved. Congratulations :boom: :100:
### You can merge and submit a project completion form from the dashboard. Good luck with the next project.
- Happy coding!

**Comment by ozovalihasan** [comment]
Thank you for your feedback @rOluochKe .

**Pull request merged**
