### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by Bluette1**
# Milestone 3: Game logic
 - Add real logic for your game - get rid of all inline comments and mocked logic used in previous milestone.
- `puts` statements exist only in main
- Encapsulate diffrent parts of game logic in classes. Do not create one class for everything.
- Follow the DRY rule
- attr_readers/attr_writers and atrr_acessors were used
- Follow the single responsibility rule
- Think of and cover all the possible edges in advance

### CODE REVIEW

**Comment by adaorachi** [comment]
### **Hi @Bluette1 and @ozovalihasan** :wave: 

Well done completing the first draft of this milestone. You both did a nice work in it. The logic looks clean, the classes have well-structured and functioning components. The implementations were properly done. Good Job.

However, there are a couple of changes to implement to get this project approved!

---
CHANGES REQUIRED :recycle: 
---

- [ ] First, ensure you make proper use of the getter and setter methods and also know when it is appropriate to use any one of them, specifically when using the attr_accessor. Kindly ensure you only use them when its usage is inevitable so as to avoid mutating their values outside the scope in which they are used. Take a look at the Board class, the board method created by the attr_accessor should be replaced by attr_reader. That value is already been mutated in the same class scope by the update_board method and is only read in the main.rb file. This is also applicable for the Game and Player attr_accessors as well.

---

- [ ]  Second, kindly make sure you follow DRY rule. In the Game class, some of the methods created by attr_accessors/attr_readers could be very much avoided and instead created in the methods you already have. For example, take a look at the attr_reader winner, you can check if there's a winner or not using the check_win method by making it return true or false. Likewise, the attr_reader current_user should also be removed and instead called as a variable in the check_player method like so  `current_user = {}`, and then called appropriately in the main.rb game flow. This is also to reduce the number of getter/setter methods and class variables used for that class.

---

The following requirements are considered optional but will be nice if you take a look at them.

- [optional] In your game flow, you inputted an option for users to change their markers but this does not exactly work alright. The markers are changed but the names are not stored and so does output the right users' names. This is only an additional feature you implemented and so, not considered a requirement  but will be nice if you fix the bug so as to make your game complete and look professional.

- [optional] Second, In the Game class methods, you should consider making use of parameters to pass in the first_player and second_player getter methods. And then, assigning them as variables in the main.rb game flow. This is to reduce the number of getter methods that are exposed and susceptible to change.

---

### **After implementing the mandatory requirements stated above, you can request for another review by submitting a code review form.**

Should you have any question, please feel free to reach out to me on Slack with the username (@adaorachi)

Good Luck and Happy Coding! :relaxed: 

**MaryAnn Chukwuka.**

**Comment by ozovalihasan** [comment]
Thanks for your good descriptive feedback @adaorachi.

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### You have done a good job and for also implementing changes from the previous reviews :clap: The project looks good. Therefore, it has been approved. congratulations :boom: :100:
### You can merge and submit a project completion form from the dashboard. Good luck with the next project.
- Happy coding!

**Comment by ozovalihasan** [comment]
Thanks for your feedback @rOluochKe.

**Pull request merged**
